INSERT INTO CAT_CLIENTE (ID_CLIENTE, NOMBRE)
VALUES(720010, 'Cliente 1')

INSERT INTO CAT_CLIENTE (ID_CLIENTE, NOMBRE)
VALUES(710020, 'Cliente 2')


INSERT INTO CAT_PRODUCTOS(ID_PRODUCTO, ACTIVO, CLAVE, DESCRIPTION)
VALUES(18156, 1, '0001ABC', 'Producto 1')

INSERT INTO CAT_PRODUCTOS(ID_PRODUCTO, ACTIVO, CLAVE, DESCRIPTION)
VALUES(10200, 1, '0002ABC', 'Producto 2')

INSERT INTO CAT_PRODUCTOS(ID_PRODUCTO, ACTIVO, CLAVE, DESCRIPTION)
VALUES(25020, 1, '0003ABC', 'Producto 3')

INSERT INTO CAT_PRODUCTOS(ID_PRODUCTO, ACTIVO, CLAVE, DESCRIPTION)
VALUES(10170, 1, '0004ABC', 'Producto 4')

INSERT INTO CAT_PRODUCTOS(ID_PRODUCTO, ACTIVO, CLAVE, DESCRIPTION)
VALUES(10280, 1, '0005ABC', 'Producto 5')

INSERT INTO CAT_PRODUCTOS(ID_PRODUCTO, ACTIVO, CLAVE, DESCRIPTION)
VALUES(30001, 1, '0006ABC', 'Producto 6')
